---
title: "Project7"
author: "Huanyu Liu"
date: "2/28/2019"
output: pdf_document
---
# Problem 1
$\Delta X = \sigma \sqrt{\Delta t}$
```{r,eval=TRUE}
library(knitr)
df1 = read.csv('problem1_1.csv')
df2 = read.csv('problem1_3.csv')
df3 = read.csv('problem1_4.csv')
df1['efd_error'] = df1$efd / df1$black.scholes - 1
df1['ifd_error'] = df1$ifd / df1$black.scholes - 1
df1['cnfd_error'] = df1$cnfd / df1$black.scholes - 1
df2['efd_error'] = df2$efd / df2$black.scholes - 1
df2['ifd_error'] = df2$ifd / df2$black.scholes - 1
df2['cnfd_error'] = df2$cnfd / df2$black.scholes - 1
df3['efd_error'] = df3$efd / df3$black.scholes - 1
df3['ifd_error'] = df3$ifd / df3$black.scholes - 1
df3['cnfd_error'] = df3$cnfd / df3$black.scholes - 1

kable(df1)
```

$\Delta X = \sigma \sqrt{3 \Delta t}$

```{r,eval= TRUE}
kable(df2)
```

$\Delta X = \sigma \sqrt{4 \Delta t}$

```{r,eval=TRUE}
kable(df3)
```


Option prices are more accurate in the middle of stock price range. In general, the result of CNFD relies in between of EFD and IFD.

# Problem 2

```{r, eval=TRUE}

plot_func = function(file,main){
  df = read.csv(file)
  plot(df$stock.price,df$efd,type = 'l',col = 1,xlab = 'stock price', ylab = 'option', main = main)
  lines(df$stock.price, df$ifd, col = 2)
  lines(df$stock.price,df$cnfd, col = 3)
  legend("bottomright", legend = c("efd", "ifd", "cnfd"), col = c(1:3), lwd = 1, cex = 0.65)
}

plot_func('problem2call_1.csv', 'American Call with delta S = 0.25')
plot_func('problem2call_4.csv', 'American Call with delta S = 1')
plot_func('problem2call_5.csv', 'American Call with delta S = 1.25')
plot_func('problem2put_1.csv', 'American Put with delta S = 0.25')
plot_func('problem2put_4.csv', 'American Put with delta S = 1')
plot_func('problem2put_5.csv', 'American Put with delta S = 1.25')


```


As delta S increases, the results get less accurate.